// app/lib/catalog/ingredientCatalog.ts

import { IngredientCatalogItem } from "./catalogTypes";

export const ingredientCatalog: IngredientCatalogItem[] = [
  {
    slug: "magnesium-glycinate",
    name: "Magnesium Glycinate",
    aliases: ["magnesium", "magnesium bisglycinate"],
    categories: ["sleep", "stress", "recovery"],
    evidenceLevel: "high",
    evidenceSummary:
      "Consistent evidence supports magnesium for sleep support, neuromuscular function, and stress-related tension in appropriate contexts.",
    scientificContext:
      "Magnesium participates in neuromuscular balance, energy metabolism, and nervous system regulation.",
    commonUseCases: ["poor sleep quality", "stress", "muscle tension", "recovery support"],
    possibleBenefits: ["sleep support", "relaxation support", "recovery support"],
    suggestedUse: {
      timing: "Often used in the evening.",
      withFood: true,
      generalDoseNote: "Use according to product label and individual tolerance.",
      durationNote: "Often evaluated over several weeks of consistent use.",
    },
    quizSignalsThatIncreaseRelevance: ["low_sleep_quality", "high_stress", "fatigue"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: ["renal impairment"],
    sideEffects: ["gastrointestinal discomfort", "loose stools in some users"],
    interactions: ["antibiotics", "diuretics"],
    avoidIf: ["severe kidney disease"],
    cautionIf: ["multiple medications", "electrolyte-related conditions"],
    qualitySignals: ["chelated form", "third-party testing", "clear elemental magnesium disclosure"],
    sourceBasis: {
      nihOds: true,
      fdaRelevant: false,
      uspRelevant: true,
      nsfRelevant: true,
    },
  },
  {
    slug: "omega-3",
    name: "Omega-3 (EPA/DHA)",
    aliases: ["fish oil", "epa dha"],
    categories: ["general", "metabolic", "recovery"],
    evidenceLevel: "high",
    evidenceSummary:
      "Omega-3 fatty acids have strong evidence in cardiovascular support contexts, especially around triglycerides.",
    scientificContext:
      "EPA and DHA participate in membrane function, inflammatory signaling, and cardiometabolic support.",
    commonUseCases: ["triglyceride support", "general cardiovascular support", "recovery support"],
    possibleBenefits: ["cardiometabolic support", "general health support"],
    suggestedUse: {
      timing: "Usually taken with meals.",
      withFood: true,
      generalDoseNote: "Check label for EPA and DHA content, not only total fish oil.",
      durationNote: "Usually considered a medium- to long-term support option.",
    },
    quizSignalsThatIncreaseRelevance: ["low_physical_activity", "poor_diet"],
    labSignalsThatIncreaseRelevance: ["high_triglycerides"],
    restrictions: ["bleeding disorders"],
    sideEffects: ["fishy aftertaste", "mild digestive discomfort"],
    interactions: ["anticoagulants"],
    avoidIf: ["fish allergy"],
    cautionIf: ["blood thinner use", "planned surgery"],
    qualitySignals: ["oxidation control", "third-party purity testing", "EPA/DHA disclosure"],
    sourceBasis: {
      nihOds: true,
      fdaRelevant: true,
      uspRelevant: true,
      nsfRelevant: true,
    },
  },
  {
    slug: "vitamin-d",
    name: "Vitamin D3",
    aliases: ["vitamin d", "cholecalciferol"],
    categories: ["general", "metabolic"],
    evidenceLevel: "high",
    evidenceSummary:
      "Vitamin D is well studied for bone health and relevant in deficiency-related contexts.",
    scientificContext:
      "Vitamin D supports calcium metabolism, bone health, and multiple regulatory pathways.",
    commonUseCases: ["low sun exposure", "low vitamin D status", "general support"],
    possibleBenefits: ["vitamin D status support", "bone and immune-related support"],
    suggestedUse: {
      timing: "Commonly taken with meals.",
      withFood: true,
      generalDoseNote: "Dose should align with baseline level and label guidance.",
      durationNote: "Periodic reassessment is advisable when used long term.",
    },
    quizSignalsThatIncreaseRelevance: ["low_sun_exposure"],
    labSignalsThatIncreaseRelevance: ["low_vitamin_d"],
    restrictions: ["hypercalcemia"],
    sideEffects: ["possible digestive discomfort at higher intakes"],
    interactions: ["calcium-related therapies"],
    avoidIf: ["vitamin D toxicity"],
    cautionIf: ["kidney conditions", "history of calcium imbalance"],
    qualitySignals: ["transparent IU labeling", "third-party testing", "oil-based formulation"],
    sourceBasis: {
      nihOds: true,
      fdaRelevant: true,
      uspRelevant: true,
      nsfRelevant: true,
    },
  },
  {
    slug: "ashwagandha",
    name: "Ashwagandha",
    aliases: ["withania somnifera"],
    categories: ["stress", "sleep"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "Evidence is moderate for stress-related support, with some data on sleep quality and perceived stress.",
    scientificContext:
      "Ashwagandha is commonly positioned as an adaptogenic ingredient in stress-support formulations.",
    commonUseCases: ["stress support", "sleep support", "fatigue under stress"],
    possibleBenefits: ["stress support", "sleep quality support"],
    suggestedUse: {
      timing: "Usually once or twice daily depending on formulation.",
      withFood: true,
      generalDoseNote: "Use according to standardized extract labeling.",
      durationNote: "Often assessed over several weeks.",
    },
    quizSignalsThatIncreaseRelevance: ["high_stress", "low_sleep_quality", "fatigue"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: ["thyroid disorders", "pregnancy"],
    sideEffects: ["digestive discomfort", "drowsiness in some users"],
    interactions: ["sedatives", "thyroid medication"],
    avoidIf: ["pregnancy"],
    cautionIf: ["thyroid disease", "autoimmune conditions", "sedative use"],
    qualitySignals: ["standardized extract", "withanolide disclosure", "third-party testing"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "coq10",
    name: "CoQ10",
    aliases: ["coenzyme q10", "ubiquinone", "ubiquinol"],
    categories: ["energy", "general", "recovery"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "Moderate evidence supports use in selected energy-related and cardiovascular support contexts.",
    scientificContext:
      "CoQ10 is involved in mitochondrial energy production and antioxidant-related processes.",
    commonUseCases: ["energy support", "recovery support", "general support"],
    possibleBenefits: ["mitochondrial support", "energy support"],
    suggestedUse: {
      timing: "Commonly taken with food.",
      withFood: true,
      generalDoseNote: "Fat-containing meals may improve absorption.",
      durationNote: "Usually assessed over weeks rather than days.",
    },
    quizSignalsThatIncreaseRelevance: ["fatigue", "low_physical_activity"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: [],
    sideEffects: ["mild digestive discomfort"],
    interactions: ["anticoagulants"],
    avoidIf: [],
    cautionIf: ["multiple cardiovascular medications"],
    qualitySignals: ["ubiquinol or clearly labeled ubiquinone form", "third-party testing"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "complex-b",
    name: "Vitamin B Complex",
    aliases: ["b-complex", "vitamin b complex"],
    categories: ["energy", "focus", "general"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "B vitamins are relevant to energy metabolism, especially when intake or status is insufficient.",
    scientificContext:
      "B vitamins support energy metabolism, nervous system function, and multiple enzymatic pathways.",
    commonUseCases: ["energy support", "general micronutrient support", "focus support"],
    possibleBenefits: ["energy metabolism support", "nervous system support"],
    suggestedUse: {
      timing: "Often taken earlier in the day.",
      withFood: true,
      generalDoseNote: "Use label guidance and avoid unnecessary megadosing.",
      durationNote: "Benefit depends on baseline need and consistency.",
    },
    quizSignalsThatIncreaseRelevance: ["fatigue", "focus_difficulty"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: [],
    sideEffects: ["bright yellow urine", "mild nausea in some users"],
    interactions: [],
    avoidIf: [],
    cautionIf: ["already using multiple fortified products"],
    qualitySignals: ["balanced formulation", "clear labeling of forms and strengths"],
    sourceBasis: {
      nihOds: true,
      fdaRelevant: false,
      uspRelevant: true,
      nsfRelevant: true,
    },
  },
  {
    slug: "melatonin",
    name: "Melatonin",
    aliases: ["melatonin supplement"],
    categories: ["sleep"],
    evidenceLevel: "high",
    evidenceSummary:
      "Melatonin is well studied for sleep onset timing and circadian-related sleep support contexts.",
    scientificContext:
      "Melatonin is a hormone involved in circadian timing and sleep-wake signaling.",
    commonUseCases: ["sleep onset support", "circadian disruption"],
    possibleBenefits: ["sleep timing support", "sleep onset support"],
    suggestedUse: {
      timing: "Usually taken shortly before intended sleep time.",
      withFood: null,
      generalDoseNote: "Use the lowest practical labeled dose first.",
      durationNote: "Often more useful for specific sleep timing issues than as a universal long-term solution.",
    },
    quizSignalsThatIncreaseRelevance: ["low_sleep_quality", "short_sleep_duration"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: ["pregnancy"],
    sideEffects: ["morning grogginess", "vivid dreams", "drowsiness"],
    interactions: ["sedatives"],
    avoidIf: ["pregnancy"],
    cautionIf: ["sedative use", "need for next-morning alertness"],
    qualitySignals: ["low-dose options", "third-party testing", "clear dose labeling"],
    sourceBasis: {
      nihOds: true,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "l-theanine",
    name: "L-Theanine",
    aliases: ["theanine"],
    categories: ["stress", "focus", "sleep"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "Moderate evidence supports calm-focus positioning and stress-related support in some contexts.",
    scientificContext:
      "L-theanine is an amino acid commonly associated with relaxed alertness support.",
    commonUseCases: ["stress support", "focus support", "calm support"],
    possibleBenefits: ["calm focus support", "stress-related support"],
    suggestedUse: {
      timing: "Often used during the day for calm focus or later for relaxation support.",
      withFood: null,
      generalDoseNote: "Use according to product labeling.",
      durationNote: "Can be used situationally or consistently depending on product guidance.",
    },
    quizSignalsThatIncreaseRelevance: ["high_stress", "focus_difficulty", "low_sleep_quality"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: [],
    sideEffects: ["mild headache", "possible drowsiness in some users"],
    interactions: ["sedatives"],
    avoidIf: [],
    cautionIf: ["very low blood pressure", "sedative combination use"],
    qualitySignals: ["clear standalone labeling", "third-party testing"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "rhodiola",
    name: "Rhodiola rosea",
    aliases: ["rhodiola"],
    categories: ["energy", "stress", "focus"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "Moderate evidence supports use in fatigue and stress-related performance contexts.",
    scientificContext:
      "Rhodiola is often categorized as an adaptogenic botanical for fatigue and stress support.",
    commonUseCases: ["fatigue support", "stress support", "focus support"],
    possibleBenefits: ["fatigue support", "mental performance support"],
    suggestedUse: {
      timing: "Usually earlier in the day.",
      withFood: true,
      generalDoseNote: "Use standardized products when possible.",
      durationNote: "Often evaluated over a few weeks.",
    },
    quizSignalsThatIncreaseRelevance: ["fatigue", "high_stress", "focus_difficulty"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: [],
    sideEffects: ["restlessness", "mild digestive upset"],
    interactions: ["stimulants"],
    avoidIf: [],
    cautionIf: ["anxiety-prone users", "stimulant stacking"],
    qualitySignals: ["standardized extract", "rosavin/salidroside disclosure"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "glycine",
    name: "Glycine",
    aliases: ["glycine powder"],
    categories: ["sleep", "recovery"],
    evidenceLevel: "limited",
    evidenceSummary:
      "Evidence is limited but promising in selected sleep and recovery-support contexts.",
    scientificContext:
      "Glycine is an amino acid involved in structural and neurotransmitter-related functions.",
    commonUseCases: ["sleep support", "recovery support"],
    possibleBenefits: ["sleep quality support", "recovery support"],
    suggestedUse: {
      timing: "Often used in the evening.",
      withFood: null,
      generalDoseNote: "Use label guidance and tolerance-based titration where appropriate.",
      durationNote: "May require consistent use to assess response.",
    },
    quizSignalsThatIncreaseRelevance: ["low_sleep_quality", "fatigue"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: [],
    sideEffects: ["digestive discomfort"],
    interactions: [],
    avoidIf: [],
    cautionIf: ["multiple amino acid supplements already in use"],
    qualitySignals: ["simple additive-light formula", "clear serving disclosure"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: false,
    },
  },
  {
    slug: "electrolytes",
    name: "Electrolytes",
    aliases: ["electrolyte mix"],
    categories: ["energy", "recovery", "general"],
    evidenceLevel: "moderate",
    evidenceSummary:
      "Electrolyte support can be relevant in hydration, heat exposure, and exercise-related contexts.",
    scientificContext:
      "Electrolytes support fluid balance, neuromuscular signaling, and performance-related hydration.",
    commonUseCases: ["hydration support", "exercise recovery", "heat exposure"],
    possibleBenefits: ["hydration support", "recovery support"],
    suggestedUse: {
      timing: "Commonly used around physical activity or heat exposure.",
      withFood: null,
      generalDoseNote: "Check sodium, potassium, and sugar content on label.",
      durationNote: "Often situational rather than universal daily use.",
    },
    quizSignalsThatIncreaseRelevance: ["fatigue", "low_physical_activity"],
    labSignalsThatIncreaseRelevance: [],
    restrictions: ["hypertension"],
    sideEffects: ["GI discomfort in some users"],
    interactions: ["blood pressure medications"],
    avoidIf: [],
    cautionIf: ["high blood pressure", "kidney issues"],
    qualitySignals: ["transparent sodium/potassium content", "low unnecessary sugar"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: true,
    },
  },
  {
    slug: "general-probiotic",
    name: "General Probiotic",
    aliases: ["probiotic", "multi-strain probiotic"],
    categories: ["general"],
    evidenceLevel: "limited",
    evidenceSummary:
      "Evidence for probiotics depends strongly on strain, dose, and intended use case.",
    scientificContext:
      "Probiotic effects are strain-specific and should not be generalized across all products.",
    commonUseCases: ["digestive support", "general wellness support"],
    possibleBenefits: ["digestive support"],
    suggestedUse: {
      timing: "Depends on product format and label instructions.",
      withFood: null,
      generalDoseNote: "Prefer products with clearly identified strains and storage guidance.",
      durationNote: "Response is variable and should be reviewed over time.",
    },
    quizSignalsThatIncreaseRelevance: [],
    labSignalsThatIncreaseRelevance: [],
    restrictions: ["severely immunocompromised state"],
    sideEffects: ["gas", "bloating"],
    interactions: [],
    avoidIf: ["severely immunocompromised state"],
    cautionIf: ["complex medical conditions"],
    qualitySignals: ["strain disclosure", "CFU transparency", "storage stability"],
    sourceBasis: {
      nihOds: false,
      fdaRelevant: false,
      uspRelevant: false,
      nsfRelevant: false,
    },
  },
];