// app/lib/catalog/productCatalog.ts

import { ProductCatalogItem } from "./catalogTypes";

function productImage(slug: string): string {
  return `/products/${slug}.webp`;
}

export const productCatalog: ProductCatalogItem[] = [
  // magnesium-glycinate
  {
    slug: "thorne-magnesium-bisglycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "Magnesium Bisglycinate",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "120 capsules",
    servings: 60,
    priceUsd: 42,
    priceLabel: "$42",
    estimatedCostPerDayUsd: 0.7,
    budgetTier: "excellent",
    qualityScore: 95,
    valueScore: 84,
    qualitySeals: ["NSF_173", "THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Marca premium reconocida",
      "Fórmula limpia",
      "Perfil orientado a calidad profesional",
    ],
    imageUrl: productImage("thorne-magnesium-bisglycinate"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "now-magnesium-glycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "Magnesium Glycinate",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "180 capsules",
    servings: 90,
    priceUsd: 25,
    priceLabel: "$25",
    estimatedCostPerDayUsd: 0.28,
    budgetTier: "very_good",
    qualityScore: 85,
    valueScore: 91,
    qualitySeals: ["GMP"],
    qualityNotes: [
      "Muy buena relación costo-beneficio",
      "Amplia disponibilidad",
    ],
    imageUrl: productImage("now-magnesium-glycinate"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "doctors-best-magnesium-glycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "High Absorption Magnesium Glycinate",
    brand: "Doctor's Best",
    manufacturer: "Doctor's Best",
    form: "tablet",
    presentation: "120 tablets",
    servings: 60,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.3,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Opción asequible de entrada"],
    imageUrl: productImage("doctors-best-magnesium-glycinate"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },

  // omega-3
  {
    slug: "nordic-naturals-ultimate-omega",
    ingredientSlug: "omega-3",
    productName: "Ultimate Omega",
    brand: "Nordic Naturals",
    manufacturer: "Nordic Naturals",
    form: "softgel",
    presentation: "60 softgels",
    servings: 30,
    priceUsd: 32,
    priceLabel: "$32",
    estimatedCostPerDayUsd: 1.06,
    budgetTier: "excellent",
    qualityScore: 94,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Marca con reputación fuerte",
      "Buena transparencia EPA/DHA",
    ],
    imageUrl: productImage("nordic-naturals-ultimate-omega"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb", "direct"],
  },
  {
    slug: "now-ultra-omega-3",
    ingredientSlug: "omega-3",
    productName: "Ultra Omega-3",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "softgel",
    presentation: "90 softgels",
    servings: 45,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.49,
    budgetTier: "very_good",
    qualityScore: 86,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor para soporte EPA/DHA"],
    imageUrl: productImage("now-ultra-omega-3"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "sports-research-omega-3",
    ingredientSlug: "omega-3",
    productName: "Omega-3 Fish Oil",
    brand: "Sports Research",
    manufacturer: "Sports Research",
    form: "softgel",
    presentation: "60 softgels",
    servings: 30,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.6,
    budgetTier: "good",
    qualityScore: 80,
    valueScore: 84,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción accesible con percepción de calidad aceptable"],
    imageUrl: productImage("sports-research-omega-3"),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // vitamin-d
  {
    slug: "thorne-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D/K2 Liquid",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "liquid",
    presentation: "30 mL",
    servings: 600,
    priceUsd: 29,
    priceLabel: "$29",
    estimatedCostPerDayUsd: 0.2,
    budgetTier: "excellent",
    qualityScore: 94,
    valueScore: 86,
    qualitySeals: ["NSF_173", "THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca premium", "Formato líquido preciso"],
    imageUrl: productImage("thorne-vitamin-d3"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D-3",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "softgel",
    presentation: "240 softgels",
    servings: 240,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.06,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 95,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy alto valor", "Fórmula sencilla"],
    imageUrl: productImage("now-vitamin-d3"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "nature-made-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D3",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "softgel",
    presentation: "220 softgels",
    servings: 220,
    priceUsd: 11,
    priceLabel: "$11",
    estimatedCostPerDayUsd: 0.05,
    budgetTier: "good",
    qualityScore: 79,
    valueScore: 92,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Muy accesible", "Alta conveniencia"],
    imageUrl: productImage("nature-made-vitamin-d3"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // ashwagandha
  {
    slug: "thorne-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 30,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.93,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento premium de estilo clínico"],
    imageUrl: productImage("thorne-ashwagandha"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha Extract",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "90 capsules",
    servings: 45,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.4,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Buena opción estandarizada por valor"],
    imageUrl: productImage("now-ashwagandha"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "youtheory-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha",
    brand: "Youtheory",
    manufacturer: "Youtheory",
    form: "tablet",
    presentation: "60 tablets",
    servings: 30,
    priceUsd: 15,
    priceLabel: "$15",
    estimatedCostPerDayUsd: 0.5,
    budgetTier: "good",
    qualityScore: 75,
    valueScore: 82,
    qualitySeals: ["GMP"],
    qualityNotes: ["Alternativa práctica y asequible"],
    imageUrl: productImage("youtheory-ashwagandha"),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // coq10
  {
    slug: "thorne-coq10",
    ingredientSlug: "coq10",
    productName: "CoQ10",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 36,
    priceLabel: "$36",
    estimatedCostPerDayUsd: 0.6,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Fórmula premium", "Alta confianza de marca"],
    imageUrl: productImage("thorne-coq10"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "qunol-coq10",
    ingredientSlug: "coq10",
    productName: "Qunol CoQ10",
    brand: "Qunol",
    manufacturer: "Quten Research Institute",
    form: "softgel",
    presentation: "120 softgels",
    servings: 120,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.23,
    budgetTier: "very_good",
    qualityScore: 85,
    valueScore: 90,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Muy buen valor y familiaridad de marca"],
    imageUrl: productImage("qunol-coq10"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "doctors-best-coq10",
    ingredientSlug: "coq10",
    productName: "CoQ10",
    brand: "Doctor's Best",
    manufacturer: "Doctor's Best",
    form: "softgel",
    presentation: "120 softgels",
    servings: 120,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.18,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Opción económica"],
    imageUrl: productImage("doctors-best-coq10"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },

  // complex-b
  {
    slug: "thorne-basic-b-complex",
    ingredientSlug: "complex-b",
    productName: "Basic B-Complex",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 80,
    qualitySeals: ["NSF_173"],
    qualityNotes: ["Alta calidad de formulación"],
    imageUrl: productImage("thorne-basic-b-complex"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-b-complex",
    ingredientSlug: "complex-b",
    productName: "B-Complex",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "100 capsules",
    servings: 100,
    priceUsd: 17,
    priceLabel: "$17",
    estimatedCostPerDayUsd: 0.17,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 91,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor", "Fórmula simple"],
    imageUrl: productImage("now-b-complex"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "nature-made-super-b-complex",
    ingredientSlug: "complex-b",
    productName: "Super B Complex",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "tablet",
    presentation: "85 tablets",
    servings: 85,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.16,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Opción masiva y accesible"],
    imageUrl: productImage("nature-made-super-b-complex"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // melatonin
  {
    slug: "thorne-melaton-3",
    ingredientSlug: "melatonin",
    productName: "Melaton-3",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.33,
    budgetTier: "excellent",
    qualityScore: 90,
    valueScore: 82,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento profesional"],
    imageUrl: productImage("thorne-melaton-3"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "natrol-melatonin",
    ingredientSlug: "melatonin",
    productName: "Melatonin",
    brand: "Natrol",
    manufacturer: "Natrol",
    form: "tablet",
    presentation: "100 tablets",
    servings: 100,
    priceUsd: 13,
    priceLabel: "$13",
    estimatedCostPerDayUsd: 0.13,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Amplia disponibilidad y practicidad"],
    imageUrl: productImage("natrol-melatonin"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "nature-made-melatonin",
    ingredientSlug: "melatonin",
    productName: "Melatonin",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "tablet",
    presentation: "90 tablets",
    servings: 90,
    priceUsd: 11,
    priceLabel: "$11",
    estimatedCostPerDayUsd: 0.12,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 89,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Entrada simple y accesible"],
    imageUrl: productImage("nature-made-melatonin"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // l-theanine
  {
    slug: "thorne-theanine",
    ingredientSlug: "l-theanine",
    productName: "Theanine",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "90 capsules",
    servings: 90,
    priceUsd: 42,
    priceLabel: "$42",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 93,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento premium para calma y enfoque"],
    imageUrl: productImage("thorne-theanine"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-l-theanine",
    ingredientSlug: "l-theanine",
    productName: "L-Theanine",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "90 capsules",
    servings: 90,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.24,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 89,
    qualitySeals: ["GMP"],
    qualityNotes: ["Buen equilibrio entre costo y calidad"],
    imageUrl: productImage("now-l-theanine"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "sports-research-l-theanine",
    ingredientSlug: "l-theanine",
    productName: "L-Theanine",
    brand: "Sports Research",
    manufacturer: "Sports Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 16,
    priceLabel: "$16",
    estimatedCostPerDayUsd: 0.27,
    budgetTier: "good",
    qualityScore: 77,
    valueScore: 84,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Alternativa práctica de menor costo"],
    imageUrl: productImage("sports-research-l-theanine"),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // rhodiola
  {
    slug: "thorne-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 91,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción adaptógena premium"],
    imageUrl: productImage("thorne-rhodiola"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.3,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 87,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buena opción intermedia"],
    imageUrl: productImage("now-rhodiola"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "gaia-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola Rosea",
    brand: "Gaia Herbs",
    manufacturer: "Gaia Herbs",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 16,
    priceLabel: "$16",
    estimatedCostPerDayUsd: 0.27,
    budgetTier: "good",
    qualityScore: 79,
    valueScore: 85,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca herbal reconocida"],
    imageUrl: productImage("gaia-rhodiola"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // glycine
  {
    slug: "thorne-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "powder",
    presentation: "250 g powder",
    servings: 50,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.56,
    budgetTier: "excellent",
    qualityScore: 90,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Formato premium de ingrediente único"],
    imageUrl: productImage("thorne-glycine"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine Powder",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "powder",
    presentation: "454 g powder",
    servings: 90,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.22,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor en formato polvo"],
    imageUrl: productImage("now-glycine"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "bulk-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine",
    brand: "Bulk Supplements",
    manufacturer: "Bulk Supplements",
    form: "powder",
    presentation: "250 g powder",
    servings: 50,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.28,
    budgetTier: "good",
    qualityScore: 74,
    valueScore: 86,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción económica en polvo"],
    imageUrl: productImage("bulk-glycine"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // electrolytes
  {
    slug: "lmnt-electrolytes",
    ingredientSlug: "electrolytes",
    productName: "Electrolyte Drink Mix",
    brand: "LMNT",
    manufacturer: "LMNT",
    form: "powder",
    presentation: "30 stick packs",
    servings: 30,
    priceUsd: 45,
    priceLabel: "$45",
    estimatedCostPerDayUsd: 1.5,
    budgetTier: "excellent",
    qualityScore: 91,
    valueScore: 72,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción premium reconocida en electrolitos"],
    imageUrl: productImage("lmnt-electrolytes"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "nuun-sport",
    ingredientSlug: "electrolytes",
    productName: "Sport Electrolyte Tablets",
    brand: "Nuun",
    manufacturer: "Nuun",
    form: "tablet",
    presentation: "40 tablets",
    servings: 40,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.5,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 86,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Formato conveniente y posicionamiento accesible"],
    imageUrl: productImage("nuun-sport"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "liquid-iv-hydration",
    ingredientSlug: "electrolytes",
    productName: "Hydration Multiplier",
    brand: "Liquid I.V.",
    manufacturer: "Liquid I.V.",
    form: "powder",
    presentation: "16 stick packs",
    servings: 16,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 1.12,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 78,
    qualitySeals: ["NONE"],
    qualityNotes: [
      "Producto popular, pero conviene revisar bien su perfil de fórmula",
    ],
    imageUrl: productImage("liquid-iv-hydration"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // general-probiotic
  {
    slug: "seed-ds-01",
    ingredientSlug: "general-probiotic",
    productName: "DS-01 Daily Synbiotic",
    brand: "Seed",
    manufacturer: "Seed Health",
    form: "capsule",
    presentation: "60 capsules",
    servings: 30,
    priceUsd: 50,
    priceLabel: "$50",
    estimatedCostPerDayUsd: 1.66,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 70,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Posicionamiento premium de simbiótico",
      "Narrativa de marca muy fuerte",
    ],
    imageUrl: productImage("seed-ds-01"),
    buyUrl: "#",
    availableMarkets: ["direct"],
  },
  {
    slug: "garden-of-life-probiotic",
    ingredientSlug: "general-probiotic",
    productName: "Dr. Formulated Probiotics",
    brand: "Garden of Life",
    manufacturer: "Garden of Life",
    form: "capsule",
    presentation: "30 capsules",
    servings: 30,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.93,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca reconocida en la categoría probiótica"],
    imageUrl: productImage("garden-of-life-probiotic"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "culturelle-digestive-daily",
    ingredientSlug: "general-probiotic",
    productName: "Digestive Daily Probiotic",
    brand: "Culturelle",
    manufacturer: "i-Health",
    form: "capsule",
    presentation: "30 capsules",
    servings: 30,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.66,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 82,
    qualitySeals: ["NONE"],
    qualityNotes: ["Opción probiótica accesible"],
    imageUrl: productImage("culturelle-digestive-daily"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
];