// app/lib/catalog/productCatalog.ts

import { ProductCatalogItem } from "./catalogTypes";

function buildProductImageDataUrl(
  brand: string,
  productName: string,
  tier: "excellent" | "very_good" | "good"
): string {
  const bg =
    tier === "excellent"
      ? "#EAF1FF"
      : tier === "very_good"
      ? "#F3F6FB"
      : "#F8FAFC";

  const accent =
    tier === "excellent"
      ? "#0F172A"
      : tier === "very_good"
      ? "#1E3A8A"
      : "#334155";

  const badge =
    tier === "excellent"
      ? "Excelente"
      : tier === "very_good"
      ? "Muy buena"
      : "Buena";

  const safeBrand = escapeXml(brand);
  const safeProduct = escapeXml(productName);
  const safeBadge = escapeXml(badge);

  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900" viewBox="0 0 1200 900">
      <rect width="1200" height="900" rx="36" fill="${bg}" />
      <rect x="48" y="48" width="1104" height="804" rx="28" fill="#FFFFFF" stroke="#D9E2EC" />
      <rect x="92" y="92" width="180" height="44" rx="22" fill="${accent}" opacity="0.08" />
      <text x="182" y="120" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" fill="${accent}">
        ${safeBadge}
      </text>
      <rect x="92" y="180" width="360" height="460" rx="32" fill="${accent}" opacity="0.05" />
      <rect x="170" y="250" width="210" height="300" rx="42" fill="#FFFFFF" stroke="${accent}" stroke-width="6" />
      <rect x="200" y="210" width="150" height="60" rx="30" fill="#FFFFFF" stroke="${accent}" stroke-width="6" />
      <circle cx="275" cy="380" r="58" fill="${accent}" opacity="0.10" />
      <rect x="215" y="472" width="120" height="18" rx="9" fill="${accent}" opacity="0.18" />
      <rect x="205" y="514" width="140" height="14" rx="7" fill="${accent}" opacity="0.12" />
      <text x="520" y="270" font-family="Arial, Helvetica, sans-serif" font-size="34" font-weight="700" fill="${accent}">
        ${safeBrand}
      </text>
      <text x="520" y="330" font-family="Arial, Helvetica, sans-serif" font-size="54" font-weight="800" fill="#0F172A">
        ${safeProduct}
      </text>
      <text x="520" y="410" font-family="Arial, Helvetica, sans-serif" font-size="24" font-weight="500" fill="#475569">
        VitaSmart AI · Vista de producto
      </text>
      <rect x="520" y="470" width="420" height="18" rx="9" fill="#E2E8F0" />
      <rect x="520" y="510" width="360" height="18" rx="9" fill="#E2E8F0" />
      <rect x="520" y="550" width="300" height="18" rx="9" fill="#E2E8F0" />
      <rect x="520" y="640" width="170" height="44" rx="22" fill="${accent}" />
      <text x="605" y="668" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" fill="#FFFFFF">
        VitaSmart
      </text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function productImage(
  brand: string,
  productName: string,
  tier: "excellent" | "very_good" | "good"
): string {
  const key = `${brand}|||${productName}`;

  const slugByProductKey: Record<string, string> = {
    "Thorne|||Magnesium Bisglycinate": "thorne-magnesium-bisglycinate",
    "NOW|||Magnesium Glycinate": "now-magnesium-glycinate",
    "Doctor's Best|||High Absorption Magnesium Glycinate":
      "doctors-best-magnesium-glycinate",

    "Nordic Naturals|||Ultimate Omega": "nordic-naturals-ultimate-omega",
    "NOW|||Ultra Omega-3": "now-ultra-omega-3",
    "Sports Research|||Omega-3 Fish Oil": "sports-research-omega-3",

    "Thorne|||Vitamin D/K2 Liquid": "thorne-vitamin-d3",
    "NOW|||Vitamin D-3": "now-vitamin-d3",
    "Nature Made|||Vitamin D3": "nature-made-vitamin-d3",

    "Thorne|||Ashwagandha": "thorne-ashwagandha",
    "NOW|||Ashwagandha Extract": "now-ashwagandha",
    "Youtheory|||Ashwagandha": "youtheory-ashwagandha",

    "Thorne|||CoQ10": "thorne-coq10",
    "Qunol|||Qunol CoQ10": "qunol-coq10",
    "Doctor's Best|||CoQ10": "doctors-best-coq10",

    "Thorne|||Basic B-Complex": "thorne-basic-b-complex",
    "NOW|||B-Complex": "now-b-complex",
    "Nature Made|||Super B Complex": "nature-made-super-b-complex",

    "Thorne|||Melaton-3": "thorne-melaton-3",
    "Natrol|||Melatonin": "natrol-melatonin",
    "Nature Made|||Melatonin": "nature-made-melatonin",

    "Thorne|||Theanine": "thorne-theanine",
    "NOW|||L-Theanine": "now-l-theanine",
    "Sports Research|||L-Theanine": "sports-research-l-theanine",

    "Thorne|||Rhodiola": "thorne-rhodiola",
    "NOW|||Rhodiola": "now-rhodiola",
    "Gaia Herbs|||Rhodiola Rosea": "gaia-rhodiola",

    "Thorne|||Glycine": "thorne-glycine",
    "NOW|||Glycine Powder": "now-glycine",
    "Bulk Supplements|||Glycine": "bulk-glycine",

    "LMNT|||Electrolyte Drink Mix": "lmnt-electrolytes",
    "Nuun|||Sport Electrolyte Tablets": "nuun-sport",
    "Liquid I.V.|||Hydration Multiplier": "liquid-iv-hydration",

    "Seed|||DS-01 Daily Synbiotic": "seed-ds-01",
    "Garden of Life|||Dr. Formulated Probiotics":
      "garden-of-life-probiotic",
    "Culturelle|||Digestive Daily Probiotic":
      "culturelle-digestive-daily",
  };

  const slug = slugByProductKey[key];

  if (slug) {
    return `/products/${slug}.webp`;
  }

  return buildProductImageDataUrl(brand, productName, tier);
}

export const productCatalog: ProductCatalogItem[] = [
  // magnesium-glycinate
  {
    slug: "thorne-magnesium-bisglycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "Magnesium Bisglycinate",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "120 capsules",
    servings: 60,
    priceUsd: 42,
    priceLabel: "$42",
    estimatedCostPerDayUsd: 0.7,
    budgetTier: "excellent",
    qualityScore: 95,
    valueScore: 84,
    qualitySeals: ["NSF_173", "THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Marca premium reconocida",
      "Fórmula limpia",
      "Perfil orientado a calidad profesional",
    ],
    imageUrl: productImage("Thorne", "Magnesium Bisglycinate", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "now-magnesium-glycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "Magnesium Glycinate",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "180 capsules",
    servings: 90,
    priceUsd: 25,
    priceLabel: "$25",
    estimatedCostPerDayUsd: 0.28,
    budgetTier: "very_good",
    qualityScore: 85,
    valueScore: 91,
    qualitySeals: ["GMP"],
    qualityNotes: [
      "Muy buena relación costo-beneficio",
      "Amplia disponibilidad",
    ],
    imageUrl: productImage("NOW", "Magnesium Glycinate", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "doctors-best-magnesium-glycinate",
    ingredientSlug: "magnesium-glycinate",
    productName: "High Absorption Magnesium Glycinate",
    brand: "Doctor's Best",
    manufacturer: "Doctor's Best",
    form: "tablet",
    presentation: "120 tablets",
    servings: 60,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.3,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Opción asequible de entrada"],
    imageUrl: productImage(
      "Doctor's Best",
      "High Absorption Magnesium Glycinate",
      "good"
    ),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },

  // omega-3
  {
    slug: "nordic-naturals-ultimate-omega",
    ingredientSlug: "omega-3",
    productName: "Ultimate Omega",
    brand: "Nordic Naturals",
    manufacturer: "Nordic Naturals",
    form: "softgel",
    presentation: "60 softgels",
    servings: 30,
    priceUsd: 32,
    priceLabel: "$32",
    estimatedCostPerDayUsd: 1.06,
    budgetTier: "excellent",
    qualityScore: 94,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Marca con reputación fuerte",
      "Buena transparencia EPA/DHA",
    ],
    imageUrl: productImage(
      "Nordic Naturals",
      "Ultimate Omega",
      "excellent"
    ),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb", "direct"],
  },
  {
    slug: "now-ultra-omega-3",
    ingredientSlug: "omega-3",
    productName: "Ultra Omega-3",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "softgel",
    presentation: "90 softgels",
    servings: 45,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.49,
    budgetTier: "very_good",
    qualityScore: 86,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor para soporte EPA/DHA"],
    imageUrl: productImage("NOW", "Ultra Omega-3", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "sports-research-omega-3",
    ingredientSlug: "omega-3",
    productName: "Omega-3 Fish Oil",
    brand: "Sports Research",
    manufacturer: "Sports Research",
    form: "softgel",
    presentation: "60 softgels",
    servings: 30,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.6,
    budgetTier: "good",
    qualityScore: 80,
    valueScore: 84,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción accesible con percepción de calidad aceptable"],
    imageUrl: productImage(
      "Sports Research",
      "Omega-3 Fish Oil",
      "good"
    ),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // vitamin-d
  {
    slug: "thorne-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D/K2 Liquid",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "liquid",
    presentation: "30 mL",
    servings: 600,
    priceUsd: 29,
    priceLabel: "$29",
    estimatedCostPerDayUsd: 0.2,
    budgetTier: "excellent",
    qualityScore: 94,
    valueScore: 86,
    qualitySeals: ["NSF_173", "THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca premium", "Formato líquido preciso"],
    imageUrl: productImage("Thorne", "Vitamin D/K2 Liquid", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D-3",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "softgel",
    presentation: "240 softgels",
    servings: 240,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.06,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 95,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy alto valor", "Fórmula sencilla"],
    imageUrl: productImage("NOW", "Vitamin D-3", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "nature-made-vitamin-d3",
    ingredientSlug: "vitamin-d",
    productName: "Vitamin D3",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "softgel",
    presentation: "220 softgels",
    servings: 220,
    priceUsd: 11,
    priceLabel: "$11",
    estimatedCostPerDayUsd: 0.05,
    budgetTier: "good",
    qualityScore: 79,
    valueScore: 92,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Muy accesible", "Alta conveniencia"],
    imageUrl: productImage("Nature Made", "Vitamin D3", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // ashwagandha
  {
    slug: "thorne-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 30,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.93,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento premium de estilo clínico"],
    imageUrl: productImage("Thorne", "Ashwagandha", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha Extract",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "90 capsules",
    servings: 45,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.4,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Buena opción estandarizada por valor"],
    imageUrl: productImage("NOW", "Ashwagandha Extract", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "youtheory-ashwagandha",
    ingredientSlug: "ashwagandha",
    productName: "Ashwagandha",
    brand: "Youtheory",
    manufacturer: "Youtheory",
    form: "tablet",
    presentation: "60 tablets",
    servings: 30,
    priceUsd: 15,
    priceLabel: "$15",
    estimatedCostPerDayUsd: 0.5,
    budgetTier: "good",
    qualityScore: 75,
    valueScore: 82,
    qualitySeals: ["GMP"],
    qualityNotes: ["Alternativa práctica y asequible"],
    imageUrl: productImage("Youtheory", "Ashwagandha", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // coq10
  {
    slug: "thorne-coq10",
    ingredientSlug: "coq10",
    productName: "CoQ10",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 36,
    priceLabel: "$36",
    estimatedCostPerDayUsd: 0.6,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Fórmula premium", "Alta confianza de marca"],
    imageUrl: productImage("Thorne", "CoQ10", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "qunol-coq10",
    ingredientSlug: "coq10",
    productName: "Qunol CoQ10",
    brand: "Qunol",
    manufacturer: "Quten Research Institute",
    form: "softgel",
    presentation: "120 softgels",
    servings: 120,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.23,
    budgetTier: "very_good",
    qualityScore: 85,
    valueScore: 90,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Muy buen valor y familiaridad de marca"],
    imageUrl: productImage("Qunol", "Qunol CoQ10", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "doctors-best-coq10",
    ingredientSlug: "coq10",
    productName: "CoQ10",
    brand: "Doctor's Best",
    manufacturer: "Doctor's Best",
    form: "softgel",
    presentation: "120 softgels",
    servings: 120,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.18,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["GMP"],
    qualityNotes: ["Opción económica"],
    imageUrl: productImage("Doctor's Best", "CoQ10", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },

  // complex-b
  {
    slug: "thorne-basic-b-complex",
    ingredientSlug: "complex-b",
    productName: "Basic B-Complex",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 80,
    qualitySeals: ["NSF_173"],
    qualityNotes: ["Alta calidad de formulación"],
    imageUrl: productImage("Thorne", "Basic B-Complex", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-b-complex",
    ingredientSlug: "complex-b",
    productName: "B-Complex",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "100 capsules",
    servings: 100,
    priceUsd: 17,
    priceLabel: "$17",
    estimatedCostPerDayUsd: 0.17,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 91,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor", "Fórmula simple"],
    imageUrl: productImage("NOW", "B-Complex", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "nature-made-super-b-complex",
    ingredientSlug: "complex-b",
    productName: "Super B Complex",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "tablet",
    presentation: "85 tablets",
    servings: 85,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.16,
    budgetTier: "good",
    qualityScore: 78,
    valueScore: 88,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Opción masiva y accesible"],
    imageUrl: productImage("Nature Made", "Super B Complex", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // melatonin
  {
    slug: "thorne-melaton-3",
    ingredientSlug: "melatonin",
    productName: "Melaton-3",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.33,
    budgetTier: "excellent",
    qualityScore: 90,
    valueScore: 82,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento profesional"],
    imageUrl: productImage("Thorne", "Melaton-3", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "natrol-melatonin",
    ingredientSlug: "melatonin",
    productName: "Melatonin",
    brand: "Natrol",
    manufacturer: "Natrol",
    form: "tablet",
    presentation: "100 tablets",
    servings: 100,
    priceUsd: 13,
    priceLabel: "$13",
    estimatedCostPerDayUsd: 0.13,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Amplia disponibilidad y practicidad"],
    imageUrl: productImage("Natrol", "Melatonin", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "nature-made-melatonin",
    ingredientSlug: "melatonin",
    productName: "Melatonin",
    brand: "Nature Made",
    manufacturer: "Nature Made",
    form: "tablet",
    presentation: "90 tablets",
    servings: 90,
    priceUsd: 11,
    priceLabel: "$11",
    estimatedCostPerDayUsd: 0.12,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 89,
    qualitySeals: ["USP_VERIFIED"],
    qualityNotes: ["Entrada simple y accesible"],
    imageUrl: productImage("Nature Made", "Melatonin", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // l-theanine
  {
    slug: "thorne-theanine",
    ingredientSlug: "l-theanine",
    productName: "Theanine",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "90 capsules",
    servings: 90,
    priceUsd: 42,
    priceLabel: "$42",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 93,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Posicionamiento premium para calma y enfoque"],
    imageUrl: productImage("Thorne", "Theanine", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-l-theanine",
    ingredientSlug: "l-theanine",
    productName: "L-Theanine",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "90 capsules",
    servings: 90,
    priceUsd: 22,
    priceLabel: "$22",
    estimatedCostPerDayUsd: 0.24,
    budgetTier: "very_good",
    qualityScore: 84,
    valueScore: 89,
    qualitySeals: ["GMP"],
    qualityNotes: ["Buen equilibrio entre costo y calidad"],
    imageUrl: productImage("NOW", "L-Theanine", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "sports-research-l-theanine",
    ingredientSlug: "l-theanine",
    productName: "L-Theanine",
    brand: "Sports Research",
    manufacturer: "Sports Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 16,
    priceLabel: "$16",
    estimatedCostPerDayUsd: 0.27,
    budgetTier: "good",
    qualityScore: 77,
    valueScore: 84,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Alternativa práctica de menor costo"],
    imageUrl: productImage("Sports Research", "L-Theanine", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon"],
  },

  // rhodiola
  {
    slug: "thorne-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.46,
    budgetTier: "excellent",
    qualityScore: 91,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción adaptógena premium"],
    imageUrl: productImage("Thorne", "Rhodiola", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 0.3,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 87,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buena opción intermedia"],
    imageUrl: productImage("NOW", "Rhodiola", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "gaia-rhodiola",
    ingredientSlug: "rhodiola",
    productName: "Rhodiola Rosea",
    brand: "Gaia Herbs",
    manufacturer: "Gaia Herbs",
    form: "capsule",
    presentation: "60 capsules",
    servings: 60,
    priceUsd: 16,
    priceLabel: "$16",
    estimatedCostPerDayUsd: 0.27,
    budgetTier: "good",
    qualityScore: 79,
    valueScore: 85,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca herbal reconocida"],
    imageUrl: productImage("Gaia Herbs", "Rhodiola Rosea", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // glycine
  {
    slug: "thorne-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine",
    brand: "Thorne",
    manufacturer: "Thorne Research",
    form: "powder",
    presentation: "250 g powder",
    servings: 50,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.56,
    budgetTier: "excellent",
    qualityScore: 90,
    valueScore: 78,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Formato premium de ingrediente único"],
    imageUrl: productImage("Thorne", "Glycine", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "now-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine Powder",
    brand: "NOW",
    manufacturer: "NOW Foods",
    form: "powder",
    presentation: "454 g powder",
    servings: 90,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.22,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 90,
    qualitySeals: ["GMP"],
    qualityNotes: ["Muy buen valor en formato polvo"],
    imageUrl: productImage("NOW", "Glycine Powder", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "iherb"],
  },
  {
    slug: "bulk-glycine",
    ingredientSlug: "glycine",
    productName: "Glycine",
    brand: "Bulk Supplements",
    manufacturer: "Bulk Supplements",
    form: "powder",
    presentation: "250 g powder",
    servings: 50,
    priceUsd: 14,
    priceLabel: "$14",
    estimatedCostPerDayUsd: 0.28,
    budgetTier: "good",
    qualityScore: 74,
    valueScore: 86,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción económica en polvo"],
    imageUrl: productImage("Bulk Supplements", "Glycine", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // electrolytes
  {
    slug: "lmnt-electrolytes",
    ingredientSlug: "electrolytes",
    productName: "Electrolyte Drink Mix",
    brand: "LMNT",
    manufacturer: "LMNT",
    form: "powder",
    presentation: "30 stick packs",
    servings: 30,
    priceUsd: 45,
    priceLabel: "$45",
    estimatedCostPerDayUsd: 1.5,
    budgetTier: "excellent",
    qualityScore: 91,
    valueScore: 72,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Opción premium reconocida en electrolitos"],
    imageUrl: productImage("LMNT", "Electrolyte Drink Mix", "excellent"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "nuun-sport",
    ingredientSlug: "electrolytes",
    productName: "Sport Electrolyte Tablets",
    brand: "Nuun",
    manufacturer: "Nuun",
    form: "tablet",
    presentation: "40 tablets",
    servings: 40,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.5,
    budgetTier: "very_good",
    qualityScore: 82,
    valueScore: 86,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Formato conveniente y posicionamiento accesible"],
    imageUrl: productImage("Nuun", "Sport Electrolyte Tablets", "very_good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "liquid-iv-hydration",
    ingredientSlug: "electrolytes",
    productName: "Hydration Multiplier",
    brand: "Liquid I.V.",
    manufacturer: "Liquid I.V.",
    form: "powder",
    presentation: "16 stick packs",
    servings: 16,
    priceUsd: 18,
    priceLabel: "$18",
    estimatedCostPerDayUsd: 1.12,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 78,
    qualitySeals: ["NONE"],
    qualityNotes: [
      "Producto popular, pero conviene revisar bien su perfil de fórmula",
    ],
    imageUrl: productImage("Liquid I.V.", "Hydration Multiplier", "good"),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },

  // general-probiotic
  {
    slug: "seed-ds-01",
    ingredientSlug: "general-probiotic",
    productName: "DS-01 Daily Synbiotic",
    brand: "Seed",
    manufacturer: "Seed Health",
    form: "capsule",
    presentation: "60 capsules",
    servings: 30,
    priceUsd: 50,
    priceLabel: "$50",
    estimatedCostPerDayUsd: 1.66,
    budgetTier: "excellent",
    qualityScore: 92,
    valueScore: 70,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: [
      "Posicionamiento premium de simbiótico",
      "Narrativa de marca muy fuerte",
    ],
    imageUrl: productImage("Seed", "DS-01 Daily Synbiotic", "excellent"),
    buyUrl: "#",
    availableMarkets: ["direct"],
  },
  {
    slug: "garden-of-life-probiotic",
    ingredientSlug: "general-probiotic",
    productName: "Dr. Formulated Probiotics",
    brand: "Garden of Life",
    manufacturer: "Garden of Life",
    form: "capsule",
    presentation: "30 capsules",
    servings: 30,
    priceUsd: 28,
    priceLabel: "$28",
    estimatedCostPerDayUsd: 0.93,
    budgetTier: "very_good",
    qualityScore: 83,
    valueScore: 80,
    qualitySeals: ["THIRD_PARTY_TESTED"],
    qualityNotes: ["Marca reconocida en la categoría probiótica"],
    imageUrl: productImage(
      "Garden of Life",
      "Dr. Formulated Probiotics",
      "very_good"
    ),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
  {
    slug: "culturelle-digestive-daily",
    ingredientSlug: "general-probiotic",
    productName: "Digestive Daily Probiotic",
    brand: "Culturelle",
    manufacturer: "i-Health",
    form: "capsule",
    presentation: "30 capsules",
    servings: 30,
    priceUsd: 20,
    priceLabel: "$20",
    estimatedCostPerDayUsd: 0.66,
    budgetTier: "good",
    qualityScore: 76,
    valueScore: 82,
    qualitySeals: ["NONE"],
    qualityNotes: ["Opción probiótica accesible"],
    imageUrl: productImage(
      "Culturelle",
      "Digestive Daily Probiotic",
      "good"
    ),
    buyUrl: "#",
    availableMarkets: ["amazon", "direct"],
  },
];